/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2019-11-18 23:54:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.mie.model.*;

public final class memberLogged_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/sidebar_loggedin.jsp", Long.valueOf(1573945146000L));
    _jspx_dependants.put("/navbar_loggedin.jsp", Long.valueOf(1573946438000L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1573934386000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<!-- Check to see if the user is logged in. Otherwise, redirect back to the login page.-->\r\n");

	session = request.getSession();
	System.out.println(session);
	if (session.getAttribute("email") == null) {
		response.sendRedirect("login.jsp");
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title>MIE350 Sample Web App - Members-Only Home Page</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Date Picker Javascript -->\r\n");
      out.write("<!-- https://jqueryui.com/datepicker/ -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/mystyle.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");

		Member member = (Member) session.getAttribute("currentSessionUser");
		System.out.print("sdf");
		String nickname = (String) session.getAttribute("nickname");
		String firstname = (String) session.getAttribute("firstname");
		String lastname = (String) session.getAttribute("lastname");
		String email = (String) session.getAttribute("email");
		String yearofbirth = (String) session.getAttribute("yob");
		String sex = (String) session.getAttribute("sex");
		String height = (String) session.getAttribute("height");
		String weight = (String) session.getAttribute("weight");
		String health = (String) session.getAttribute("healthcon");
		String objective = (String) session.getAttribute("obj");
		
	
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("<nav class=\"navbar navbar-inverse\" style=\"background-color: #DDF7ED; text-color: black;\">\r\n");
      out.write("\t<div class=\"container-fluid-center\">\r\n");
      out.write("\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\tdata-target=\"#myNavbar\">\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\"><b>SNACKKR</b></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t<li><a href=\"index_logged.jsp\"><b>Home</b></a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"about_logged.jsp\"><b>About</b></a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"CalculateFood.jsp\"><b>Search Food & Calculate</b></a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"foodRecommend.jsp\"><b>Food Recommendation</b></a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"searchARecipe.jsp\"><b>Search A Recipe & Calculate</b></a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"recipeRecommend.jsp\"><b>Recipes Recommendation</b></a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"contact_logged.jsp\"><b>Contact</b></a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<!-- The following code can be added to include a Login button to the right-hand side of the navbar-->\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\"><a data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\t\thref=\"memberLogged.jsp\"><b>Welcome, ");
      out.print(firstname);
      out.write(' ');
      out.print(lastname);
      out.write("!</b><b class=\"caret\"></b></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"memberLogged.jsp\">My profile</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"LogoutServlet\"><span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-log-out\"></span> Logout</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container-fluid text-center\">\r\n");
      out.write("\t\t<div class=\"row content\">\r\n");
      out.write("\t\t\t");
      out.write("<div class=\"col-sm-2 sidenav\">\r\n");
      out.write("\t<!-- You can put left sidebar links here if you want to. -->\r\n");
      out.write("\t<!-- Eclipse will underline the first name, last name, and user name variables as errors\r\n");
      out.write("\tbut you can ignore them since this JSP file will be imported by another JSP \r\n");
      out.write("\tfile that handles the variable declarations (see memberLogged.jsp for example).\r\n");
      out.write("\t -->\r\n");
      out.write("\t\r\n");
      out.write("\tWelcome, <b>");
      out.print(firstname);
      out.write(' ');
      out.print(lastname);
      out.write("</b> (Nickname: <b>");
      out.print(nickname);
      out.write("</b>).<br />\r\n");
      out.write("\t<br /> The time is now <b>");
      out.print(new java.util.Date());
      out.write("</b>.<br /> <br />\r\n");
      out.write("\tThe log out button can be found from drop-down menu on the upper right section of the\r\n");
      out.write("\tnavigation bar.\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-sm-10 text-left\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<h1><i>\r\n");
      out.write("\t\t\t\t\tWelcome,\r\n");
      out.write("\t\t\t\t\t");
      out.print(firstname);
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      out.print(lastname);
      out.write("!\r\n");
      out.write("\t\t\t\t</i></h1>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tWelcome to SNAKKER members-only page.\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<h2>Account Profile</h2> <a href = editprofile.jsp><b><u>Edit your profile here.</u></b></a> \r\n");
      out.write("\t\t\t\t<h4>Your information are listed below: </h4>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t<!-- should add action here, to a member controller I think -->\r\n");
      out.write("\t\t\t\t<form action = \"EditAnAccountcontroller\">\r\n");
      out.write("\t\t\t\t\t<!-- first name, last name, age, email, sex, height, weight, health condition, objectives) -->\r\n");
      out.write("\t\t\t\t\tEmail (cannot change): <br /><input type = \"text\" name = \"e\" value = ");
      out.print(email );
      out.write(" readonly /><br>\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\tNickname: <br /><input type = \"text\" name = \"un\" value = ");
      out.print(nickname);
      out.write(" readonly /><br>\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\tFirst Name: <br /><input type = \"text\" name = \"fn\" value = ");
      out.print(firstname );
      out.write(" readonly /><br>\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\tLast Name: <br /><input type = \"text\" name = \"ln\" value = ");
      out.print(lastname );
      out.write(" readonly /><br>\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\tYear of Birth: <br /><input type = \"text\" name = \"age\" value = ");
      out.print(yearofbirth );
      out.write(" readonly /><br>\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\tSex (M or F which means Male or Female): <br /><input type = \"text\" name = \"sex\" value = ");
      out.print(sex );
      out.write(" readonly /><br>\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\tHeight (in cm): <br /><input type = \"text\" name = \"h\" value = ");
      out.print(height );
      out.write(" readonly /><br>\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\tWeight (in kg): <br /><input type = \"text\" name = \"w\" value = ");
      out.print(weight );
      out.write(" readonly /><br>\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\tHealth Condition: <br /><input type = \"text\" size = 100 maxlength = 90 name = \"Hc\" value = ");
      out.print(health );
      out.write(" readonly /><br>\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\tObjectives: <br /><input type = \"text\" size = 100 maxlength = 90 name = \"o\" value = ");
      out.print(objective );
      out.write(" readonly /><br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("<footer class=\"container-fluid text-center\" style= \"background-color: #DDF7ED; color: grey;\">\r\n");
      out.write("\t<p>\r\n");
      out.write("\t\tThis sample web app is for demonstration purposes only. <br>\r\n");
      out.write("\t\tMIE350 Sample Web Application &#169;\r\n");
      out.write("\t\t");
      out.print(new java.text.SimpleDateFormat("yyyy")
					.format(new java.util.Date()));
      out.write("\r\n");
      out.write("\t\tUniversity of Toronto <br /> \r\n");
      out.write("\t\tSample: MIE350 SNACKKR <br />\r\n");
      out.write("\t\tTeam member: Stawberry, Nachos, Avocado, Coffee, Krab, Kiwi, Rice <br />\r\n");
      out.write("\t\tBootstrap Theme &#169; <a\r\n");
      out.write("\t\t\thref=\"http://getbootstrap.com/\">Bootstrap</a><br /> JavaScript for\r\n");
      out.write("\t\tTable Sorting &#169; <a\r\n");
      out.write("\t\t\thref=\"https://kryogenix.org/code/browser/sorttable/\">Stuart\r\n");
      out.write("\t\t\tLangridge</a><br />\r\n");
      out.write("\t\t\tJavaScript for Date Picker &#169; <a href=\"https://jqueryui.com/datepicker/\">https://jqueryui.com/datepicker/</a>\r\n");
      out.write("\t</p>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
